schema = 3

[mod]
  [mod.'code.linenisgreat.com/chrest/go']
    version = 'v0.0.0-20251227143500-74c5a283b63c'
    hash = 'sha256-PYFrdleAft6B2eTgGdPKZ18b6QFCjfmm8tehuRtHSDg='

  [mod.'filippo.io/age']
    version = 'v1.2.1'
    hash = 'sha256-9ZJdrmqBj43zSvStt0r25wjSfnvitdx3GYtM3urHcaA='

  [mod.'filippo.io/edwards25519']
    version = 'v1.1.0'
    hash = 'sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc='

  [mod.'github.com/DataDog/zstd']
    version = 'v1.5.7'
    hash = 'sha256-GlSZOyix7Ct7tOKmSKpGckDjMhTtiYPBTpoWdwGLx5M='

  [mod.'github.com/akutz/memconn']
    version = 'v0.1.0'
    hash = 'sha256-WOs/RQYjQbn41ui8ztHgWSd4jxydE+fvIrl/0dmHD9Y='

  [mod.'github.com/atotto/clipboard']
    version = 'v0.1.4'
    hash = 'sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/brandondube/tai']
    version = 'v0.1.0'
    hash = 'sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50='

  [mod.'github.com/catppuccin/go']
    version = 'v0.3.0'
    hash = 'sha256-otcMhI62ezoKGqzG7Owi/NROep7O0voJxp6bwXYg9+Q='

  [mod.'github.com/charmbracelet/bubbles']
    version = 'v0.21.1-0.20251124105314-ff8b5a8e17c9'
    hash = 'sha256-R4s1BHQpl2PHVLTl+7Zn/W5B4RPrNhaNhoPyOOU/P/4='

  [mod.'github.com/charmbracelet/bubbletea']
    version = 'v1.3.10'
    hash = 'sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.1'
    hash = 'sha256-d/NjM/ybG+bGRRRMMcjbPCFGFS5noZRMaL05Ix5r/II='

  [mod.'github.com/charmbracelet/huh']
    version = 'v0.8.0'
    hash = 'sha256-QMn6Ki/p7e4H1fcxGLKhR+Ja28NVm/44nDqeWS4fzEE='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.0'
    hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.3'
    hash = 'sha256-MJW53Z/WEkUYe1Kg+nbNtfnzTQexrP2lHZKJRwwH+vE='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.14'
    hash = 'sha256-NRHGlYvCsoceP9aNYLWLKdkK4j5AMHHTPR4mil1xZTs='

  [mod.'github.com/charmbracelet/x/exp/strings']
    version = 'v0.0.0-20251215102626-e0db08df7383'
    hash = 'sha256-h3coiPVi1KfgbSDCSLJV7SSKoGpnEgftylby+jOE0WA='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.6.2'
    hash = 'sha256-BZ6sBZJXzS50do3OLK0UApMz/KVV7jnLEcyddWJ1Q1w='

  [mod.'github.com/clipperhouse/stringish']
    version = 'v0.1.1'
    hash = 'sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.3.0'
    hash = 'sha256-dLL70mEOxrmYVoQjy2K7QvZiahAlJKOcFDz2mW/R/Do='

  [mod.'github.com/coder/websocket']
    version = 'v1.8.14'
    hash = 'sha256-3lTpVWweJJ+VjIIwcK9Ca+mWrbAYPxi4tx7anP1sFYw='

  [mod.'github.com/dblohm7/wingoes']
    version = 'v0.0.0-20250822163801-6d8e6105c62d'
    hash = 'sha256-G3owi1TZsUPNdBQtJ9bBmHl8vledkU5IEOn2z0eTDF8='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/erikgeiser/coninput']
    version = 'v0.0.0-20211004153227-1c3628e74d0f'
    hash = 'sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU='

  [mod.'github.com/fxamacker/cbor/v2']
    version = 'v2.9.0'
    hash = 'sha256-/IZK76MRCrz9XCiilieH5tKaLnIWyPJhwxDoVKB8dFc='

  [mod.'github.com/go-json-experiment/json']
    version = 'v0.0.0-20251027170946-4849db3c2f7e'
    hash = 'sha256-exJFEXvuuqr//7kUf3XTxz4srpUfExTiBqfnchx9ux4='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/shlex']
    version = 'v0.0.0-20191202100458-e7afc7fbc510'
    hash = 'sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM='

  [mod.'github.com/gorilla/mux']
    version = 'v1.8.1'
    hash = 'sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0='

  [mod.'github.com/hdevalence/ed25519consensus']
    version = 'v0.2.0'
    hash = 'sha256-KTbeKMOT/HCJjDHqyciQjJPPgpNk6H0VyQCCbeGgs7Y='

  [mod.'github.com/jsimonetti/rtnetlink']
    version = 'v1.4.2'
    hash = 'sha256-oVYuxjGPc3bvQ/53KG2XAC2ITdTO6pACeyjxxTJzqKY='

  [mod.'github.com/kr/fs']
    version = 'v0.1.0'
    hash = 'sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-localereader']
    version = 'v0.0.1'
    hash = 'sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.19'
    hash = 'sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE='

  [mod.'github.com/mdlayher/netlink']
    version = 'v1.8.0'
    hash = 'sha256-gLjyQMouRJgrpZ4SVeILtsOvIG0Oh/9mRxNsN9V5zBw='

  [mod.'github.com/mdlayher/socket']
    version = 'v0.5.1'
    hash = 'sha256-S2G737UU2z/8u4rOK04zGThf9sTI87TFxFg6p+HVBq8='

  [mod.'github.com/mitchellh/go-ps']
    version = 'v1.0.0'
    hash = 'sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY='

  [mod.'github.com/mitchellh/hashstructure/v2']
    version = 'v2.0.2'
    hash = 'sha256-O4Yw4pPQECWe8DoVDIH2nUMN8Zl8waS7/O1sv18M2Xs='

  [mod.'github.com/muesli/ansi']
    version = 'v0.0.0-20230316100256-276c6243b2f6'
    hash = 'sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

  [mod.'github.com/pkg/sftp']
    version = 'v1.13.10'
    hash = 'sha256-YKjTWim2Qa6z3FA1dUFaKXSRxB4fsHDAG0GL17ZDE4U='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/tailscale/go-winio']
    version = 'v0.0.0-20231025203758-c4f33415bf55'
    hash = 'sha256-WFW20c02gIk2MhafeVVNydmSfszPZegshDd2Y5abGgY='

  [mod.'github.com/x448/float16']
    version = 'v0.8.4'
    hash = 'sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/gopher-lua']
    version = 'v1.1.1'
    hash = 'sha256-f7clAQeOHKQ3pL9ibNgXvc9QnIEvlMzm5SlWEDkj5tk='

  [mod.'go4.org/mem']
    version = 'v0.0.0-20240501181205-ae6ca9944745'
    hash = 'sha256-GuSI6u7KRA6zHr/ZnWA2a24k2naETKBTpyB2A0NVS8A='

  [mod.'go4.org/netipx']
    version = 'v0.0.0-20231129151722-fdeea329fbba'
    hash = 'sha256-qFrVlacz5R3Lpkzqeg1/1MYew3DJzY9hG0Uh/ua+SOU='

  [mod.'golang.org/x/crypto']
    version = 'v0.46.0'
    hash = 'sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20251219203646-944ab1f22d93'
    hash = 'sha256-0n6AiDMlSiV2jc4+J2RrseVv7oypKO9q1ZUZuaC8wrM='

  [mod.'golang.org/x/net']
    version = 'v0.48.0'
    hash = 'sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.39.0'
    hash = 'sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U='

  [mod.'golang.org/x/term']
    version = 'v0.38.0'
    hash = 'sha256-46mX91XGJqii6SUESiU5mLVJDBOfKYCp+408m91hrMw='

  [mod.'golang.org/x/text']
    version = 'v0.32.0'
    hash = 'sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs='

  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='

  [mod.'golang.zx2c4.com/wireguard/windows']
    version = 'v0.5.3'
    hash = 'sha256-wcJWS/4Fqbc+1RHSntex0zBdlHiZfzrea4QabYkNKvU='

  [mod.'tailscale.com']
    version = 'v1.92.4'
    hash = 'sha256-8DUKcBVuGpUdG0W3o2fvNHjllxDOPcQ4a8QTqGOput4='
